"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Plus } from "lucide-react";
import { createRisk, updateRiskStatus } from "@/lib/actions";
import type { Department, Risk } from "@/lib/types";

const levels = ["low", "medium", "high"];
const statuses = ["open", "mitigating", "escalated", "closed"];
const badge: Record<string, string> = { low: "bg-slate-100 text-slate-700", medium: "bg-amber-100 text-amber-800", high: "bg-red-100 text-red-800", open: "bg-slate-100 text-slate-700", mitigating: "bg-blue-100 text-blue-800", escalated: "bg-red-100 text-red-800", closed: "bg-green-100 text-green-800" };

export function RiskRegister({ risks, departments, editable }: { risks: (Risk & { departments: { name: string } | null })[]; departments: Department[]; editable: boolean }) {
  const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(null); const result = await createRisk(new FormData(event.currentTarget)); if (result?.error) { setError(result.error); setLoading(false); return; } setOpen(false); setLoading(false); }
  return <div className="space-y-3">
    {editable && <div className="flex justify-end"><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm"><Plus className="h-4 w-4" /> Log Risk</Button></DialogTrigger><DialogContent className="max-w-xl"><DialogHeader><DialogTitle>Log Risk</DialogTitle></DialogHeader><form onSubmit={create} className="space-y-3">{error && <p className="rounded bg-destructive/10 p-2 text-sm text-destructive">{error}</p>}<div className="grid gap-3 sm:grid-cols-2"><Field label="Title" name="title" required /><div className="space-y-1"><Label htmlFor="department_id">Department</Label><select id="department_id" name="department_id" className="h-9 w-full rounded-md border bg-background px-3 text-sm"><option value="">Organisation-wide</option>{departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></div></div><div className="space-y-1"><Label htmlFor="description">Description</Label><Textarea id="description" name="description" rows={2} /></div><div className="grid gap-3 sm:grid-cols-3"><Field label="Category" name="category" defaultValue="operational" /><SelectField label="Likelihood" name="likelihood" values={levels} /><SelectField label="Impact" name="impact" values={levels} /></div><div className="grid gap-3 sm:grid-cols-3"><Field label="Owner" name="owner" /><Field label="Due date" name="due_date" type="date" /><Field label="Mitigation effectiveness (%)" name="mitigation_effectiveness" type="number" defaultValue="0" /></div><div className="space-y-1"><Label htmlFor="mitigation_plan">Mitigation plan</Label><Textarea id="mitigation_plan" name="mitigation_plan" rows={2} /></div><input type="hidden" name="status" value="open" /><Button className="w-full" disabled={loading}>{loading ? "Saving..." : "Log risk"}</Button></form></DialogContent></Dialog></div>}
    {risks.length === 0 ? <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">No risks logged yet.</CardContent></Card> : risks.map((risk) => <RiskCard key={risk.id} risk={risk} editable={editable} />)}
  </div>;
}

function RiskCard({ risk, editable }: { risk: Risk & { departments: { name: string } | null }; editable: boolean }) {
  const [status, setStatus] = useState(risk.status); const [effectiveness, setEffectiveness] = useState(String(risk.mitigation_effectiveness)); const [saving, setSaving] = useState(false);
  async function save() { setSaving(true); await updateRiskStatus(risk.id, status, Number(effectiveness)); setSaving(false); }
  return <Card><CardHeader className="pb-2"><div className="flex flex-wrap items-start justify-between gap-2"><div><CardTitle className="text-base">{risk.title}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{risk.departments?.name ?? "Organisation-wide"}{risk.owner && ` · Owner: ${risk.owner}`}{risk.due_date && ` · Due: ${risk.due_date}`}</p></div><div className="flex gap-1"><span className={`rounded px-2 py-1 text-xs capitalize ${badge[risk.likelihood]}`}>Likelihood: {risk.likelihood}</span><span className={`rounded px-2 py-1 text-xs capitalize ${badge[risk.impact]}`}>Impact: {risk.impact}</span><span className={`rounded px-2 py-1 text-xs capitalize ${badge[risk.status]}`}>{risk.status}</span></div></div></CardHeader><CardContent className="space-y-3">{risk.description && <p className="text-sm">{risk.description}</p>}{risk.mitigation_plan && <p className="text-sm text-muted-foreground"><span className="font-medium text-foreground">Mitigation:</span> {risk.mitigation_plan}</p>}<div><div className="mb-1 flex justify-between text-xs text-muted-foreground"><span>Mitigation effectiveness</span><span>{risk.mitigation_effectiveness}%</span></div><div className="h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-green-600" style={{ width: `${risk.mitigation_effectiveness}%` }} /></div></div>{editable && <div className="flex flex-wrap items-end gap-2 border-t pt-3"><div><Label className="text-xs">Status</Label><select value={status} onChange={(e) => setStatus(e.target.value as Risk["status"])} className="mt-1 h-8 rounded border bg-background px-2 text-xs">{statuses.map((value) => <option key={value} value={value}>{value}</option>)}</select></div><div><Label className="text-xs">Effectiveness</Label><Input value={effectiveness} onChange={(e) => setEffectiveness(e.target.value)} type="number" min="0" max="100" className="mt-1 h-8 w-20 text-xs" /></div><Button size="sm" onClick={save} disabled={saving}>{saving ? "Saving..." : "Update"}</Button></div>}</CardContent></Card>;
}
function Field({ label, name, type = "text", defaultValue, required }: { label: string; name: string; type?: string; defaultValue?: string; required?: boolean }) { return <div className="space-y-1"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} defaultValue={defaultValue} required={required} min={type === "number" ? "0" : undefined} /></div>; }
function SelectField({ label, name, values }: { label: string; name: string; values: string[] }) { return <div className="space-y-1"><Label htmlFor={name}>{label}</Label><select id={name} name={name} defaultValue="medium" className="h-9 w-full rounded-md border bg-background px-3 text-sm">{values.map((value) => <option key={value} value={value}>{value}</option>)}</select></div>; }
